blank_issues_enabled: true
contact_links:
  - name: TTC Community Discussion
    url: https://github.com/TheTrainerCorner/Issues/discussions
    about: For general questions and community discussions
